### ISSUE TITLE
Create function that calls panel data from API using R code as input

### ISSUE THREAD

**Issue by isabelrem** [isabelrem/2023-Software-Development-Assessment#7]
Doesn't seem to be an endpoint for this in the documentation - however, we could use the test directory xml to convert between R code and Clinical Indication column.

**Comment by isabelrem** [comment]
Created function using Tom's call API data using disease description script as template. Submitted pull request for branch 7. Now going to write file where the R_code input is tested - does it begin with capital R? is the format correct? Between 2-3 digits? (3-4 including the R)

**Comment by jessicakan789** [comment]
Done
